config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  post 'user_token' => 'user_token#create'
  mount VocabularyAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  get 'admin' => 'control_panel#index_users', :as => :admin
  get 'admin/themes' => 'control_panel#index_themes'
  resource :control_panel, only: [:index]

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :themes, only: [:create, :destroy]
  resources :words, only: [:show, :edit, :update, :destroy]

  resources :themes, only: [:index, :create, :destroy]

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :words

  validates :name, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_words

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :login, presence: true, length: { maximum: 50 },
                    uniqueness: { case_sensitive: true }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  after_create { NotificationMailer.new_user(self).deliver }
end

app/models/user_word.rb
class UserWord < ApplicationRecord
  include Filterable
  include PgSearch

  belongs_to :user
  belongs_to :word

  has_attached_file :image, default_url: 'missing.png'
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  do_not_validate_attachment_file_type :image

  scope :recent, -> { order(:created_at).reverse }
  scope :shared, -> (shared){ where share: shared }
  scope :learn, -> (learn){ where learned: learn }
  scope :category, -> (category_name){ joins(word: :theme).where('themes.name = ?', category_name) }

  pg_search_scope :search_by_transcription, :against => :transcription
  pg_search_scope :search_by_translation,
                  :against => :translation,
                  :using => {
                      :tsearch => {:prefix => true}
                  }
  pg_search_scope :search_by_word,
                  :associated_against => { :word => :name },
                  :using => {
                      :tsearch => {:prefix => true}
                  }

end

app/models/word.rb
class Word < ApplicationRecord
  include PgSearch

  belongs_to :theme
  has_many :user_words

  validates :name, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery with: :reset_session
  include Knock::Authenticable
#  include SessionsHelper
end

app/controllers/control_panel_controller.rb
class ControlPanelController < ApplicationController

  http_basic_authenticate_with :name => ENV['CP_USER'], :password => ENV['CP_PASSWORD']

  def index_users
    @users = User.all
  end

  def index_themes
    @themes = Theme.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_login(params[:login])
    if @user && @user.authenticate(params[:password])
      log_in @user
      respond_to do |format|
        format.html { redirect_to @user }
        msg = { message: 'Success' }
        format.json { render json: msg, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        msg = { message: 'error' }
        format.json { render json: msg, status: :unauthorized}
      end
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:edit, :update, :destroy]

  def themes
  end

  def edit
  end

  def update
  end

  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to admin_themes_path, notice: 'Theme was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def new
  end

  def create
    @theme = Theme.new(theme_params)
    @theme.save
    respond_to do |format|
      format.html { redirect_to admin_themes_path }
      format.js
    end
  end

  private

  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:name)
  end
end

app/controllers/user_token_controller.rb
class UserTokenController < Knock::AuthTokenController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
    if current_user
      set_user
    else
      redirect_to root_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user }
        msg = { message: 'Success' }
        format.json { render json: msg, status: :created}
      else
        format.html { render 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  def check
    email_found = User.where(email: params[:email]).count > 0
    login_found = User.where(login: params[:login]).count > 0
    message = (email_found || login_found) ? "true" : "false"
    render json: { message: message }
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.permit(:login, :name, :email, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_panel_helper.rb
module ControlPanelHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/control_panel/index_themes.html.erb
<body>
<div class="container">
  <h4 class="blog-post-title"><%= link_to 'Users', admin_url %></h4>
  <h4 class="blog-post-title"><%= link_to 'Themes', admin_themes_path %></h4>
  <div class="blog-header">
    <h1 class="blog-title">All themes</h1>
  </div>

  <div class="row">
    <div class="col-sm-8 blog-main">
      <% @themes.each do |theme| %>
          <h3 class="blog-post-title">
            <%= theme.name %>
            <%= link_to 'Delete', theme, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %>
          </h3>
      <% end %>
    </div>

    <br>
  </div>

  <div class="well">
        <%= form_for Theme.new, url: themes_path, remote: true, :html => {:role=> 'form'} do |f| %>
            <p>
              <%= f.label :name, "New theme" %><br/>
            <div class="form-group">
              <%= f.text_field :name, class: 'form-control'%>
            </div>
            </p>
            <p><%= f.submit "Add theme", class: 'btn btn-primary' %></p>
        <% end %>
  </div>

</div>
</body>

app/views/control_panel/index_users.html.erb
<body>
<div class="container">
  <h4 class="blog-post-title"><%= link_to 'Users', admin_url %></h4>
  <h4 class="blog-post-title"><%= link_to 'Themes', admin_themes_path %></h4>
  <div class="blog-header">
    <h1 class="blog-title">All users</h1>
  </div>

  <div class="row">
    <div class="col-sm-8 blog-main">
      <% @users.each do |user| %>
            <h3 class="blog-post-title"><%= user.name %>    <%= user.email %> </h3>
            <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %>
      <% end %>
    </div>

    <br>
  </div>

</div>
</body>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>
<%= form_for(@user, url: signup_path) do |f| %>

  <% if @user.errors.any? %>
    <h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :login %>
  <%= f.text_field :login %>
  <br />

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :email %>
  <%= f.email_field :email %>
  <br />

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br />

  <%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation %>
  <br />

  <%= f.submit 'Create my account' %>
<% end %>
<%= button_to 'Home', root_path, :method => 'get' %>

app/views/users/show.html.erb
<%= @user.login %>
<br />
<%= @user.name %>
<br />
<%= @user.email %>

app/views/welcome/index.html.erb
<h3>API for PERSONAL VOCABULARY</h3>

<a href="https://personal-vocabulary-beta.herokuapp.com/swagger">Link to swagger API</a>
<br>
<a href="https://personal-vocabulary-beta.herokuapp.com/sidekiq">Link to sidekiq backgroud work</a>
<br>
<a href="https://personal-vocabulary-beta.herokuapp.com/admin">Link to admin page</a>

app/views/words/index.html.erb
<body>
<div class="container">
  <div>
    <h1>Words</h1>
  </div>

  <div class="row">
    <div>
      <% @words.each do |word| %>
          <div>
            <h2><%= word.name %></h2>
            <p>Author: <%= word.user.name %></p>
            <p><%= word.transcription %></p>
            <p><%= word.translation %></p>
            <p><%= word.associate %></p>
            <p><%= word.phrase %></p>
            <%= image_tag word.image.url %>
          </div>
      <% end %>

      <%= link_to 'New Word', new_word_path, :class => 'btn btn-primary post' %>
    </div>

    <br>
  </div>

</div>
</body>

app/views/words/new.html.erb
<%= form_for @word, url: words_path, html: { multipart: true } do |f| %>

    <% if @word.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@word.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @word.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br>
    <fieldset>
      <div class="form-group">
        <%= f.label :name, :for => 'textinput' %>
        <div class="col-md-4"><%= f.text_field :name %></div>
      </div>

      <div class="form-group">
        <%= f.label :transcription, :for => 'textinput' %>
        <div class="col-md-4"><%= f.text_field :transcription%></div>
      </div>

      <div class="form-group">
        <%= f.label :translation, :for => 'textinput' %>
        <div class="col-md-4"><%= f.text_field :translation %></div>
      </div>

      <div class="form-group">
        <%= f.label :associate, :for => 'textarea'%><br>
        <div class="col-md-4"><%= f.text_area :associate %></div>
      </div>

      <div class="form-group">
        <%= f.label :phrase, :for => 'textarea'%><br>
        <div class="col-md-4"><%= f.text_area :phrase %></div>
      </div>

      <div class="form-group">
        <%= f.label :image %><br>
        <%= f.file_field :image %>
      </div>

      <div class="form-group">
        <label class="col-md-4 control-label" for="singlebutton"></label>
        <div>
          <div class="actions">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      </div>

    </fieldset>
<% end %>